routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('users', 'UserController');

Route::group(['prefix' => 'members'], function () {
    Route::resource('sellers', 'Members\sellerController', ["as" => 'members']);
    Route::get('courses/displayV/{id}', 'Members\courseController@display')->name('courses.display');
    //members.courses.display
    Route::resource('courses', 'Members\courseController', ["as" => 'members']);
    Route::resource('customers', 'Members\customerController', ["as" => 'members']);
    Route::resource('reservationOrders', 'Members\reservationOrderController', ["as" => 'members']);
    Route::resource('purchaseOrders', 'Members\purchaseOrderController', ["as" => 'members']);
});

Route::resource('api', 'apiController');

Route::resource('drons', 'dronController');

Route::resource('missions', 'missionController');

Route::resource('data', 'dataController');

app/Http/Controllers/Members/courseController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Requests\Members\CreatecourseRequest;
use App\Http\Requests\Members\UpdatecourseRequest;
use App\Repositories\Members\courseRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class courseController extends AppBaseController
{
    /** @var  courseRepository */
    private $courseRepository;

    public function __construct(courseRepository $courseRepo)
    {
        $this->courseRepository = $courseRepo;
    }

    /**
     * Display a listing of the course.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->courseRepository->pushCriteria(new RequestCriteria($request));
        $courses = $this->courseRepository->all();

        return view('members.courses.index')
            ->with('courses', $courses);
    }

    /**
     * Show the form for creating a new course.
     *
     * @return Response
     */
    public function create()
    {
        return view('members.courses.create');
    }

    /**
     * Store a newly created course in storage.
     *
     * @param CreatecourseRequest $request
     *
     * @return Response
     */
    public function store(CreatecourseRequest $request)
    {
        $input = $request->all();

        $course = $this->courseRepository->create($input);

        Flash::success('Course saved successfully.');

        return redirect(route('members.courses.index'));
    }

    /**
     * Display the specified course.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $course = $this->courseRepository->findWithoutFail($id);

        if (empty($course)) {
            Flash::error('Course not found');

            return redirect(route('members.courses.index'));
        }

        return view('members.courses.show')->with('course', $course);
    }

    /**
     * Display the specified course.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function display($id)
    {
        $course= "testing...";
        return view('members.user.courses.course-details')->with('course', $id);
    }

    /**
     * Show the form for editing the specified course.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $course = $this->courseRepository->findWithoutFail($id);

        if (empty($course)) {
            Flash::error('Course not found');

            return redirect(route('members.courses.index'));
        }

        return view('members.courses.edit')->with('course', $course);
    }

    /**
     * Update the specified course in storage.
     *
     * @param  int              $id
     * @param UpdatecourseRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatecourseRequest $request)
    {
        $course = $this->courseRepository->findWithoutFail($id);

        if (empty($course)) {
            Flash::error('Course not found');

            return redirect(route('members.courses.index'));
        }

        $course = $this->courseRepository->update($request->all(), $id);

        Flash::success('Course updated successfully.');

        return redirect(route('members.courses.index'));
    }

    /**
     * Remove the specified course from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $course = $this->courseRepository->findWithoutFail($id);

        if (empty($course)) {
            Flash::error('Course not found');

            return redirect(route('members.courses.index'));
        }

        $this->courseRepository->delete($id);

        Flash::success('Course deleted successfully.');

        return redirect(route('members.courses.index'));
    }
}

app/Http/Controllers/Members/customerController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Requests\Members\CreatecustomerRequest;
use App\Http\Requests\Members\UpdatecustomerRequest;
use App\Repositories\Members\customerRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class customerController extends AppBaseController
{
    /** @var  customerRepository */
    private $customerRepository;

    public function __construct(customerRepository $customerRepo)
    {
        $this->customerRepository = $customerRepo;
    }

    /**
     * Display a listing of the customer.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->customerRepository->pushCriteria(new RequestCriteria($request));
        $customers = $this->customerRepository->all();

        return view('members.customers.index')
            ->with('customers', $customers);
    }

    /**
     * Show the form for creating a new customer.
     *
     * @return Response
     */
    public function create()
    {
        return view('members.customers.create');
    }

    /**
     * Store a newly created customer in storage.
     *
     * @param CreatecustomerRequest $request
     *
     * @return Response
     */
    public function store(CreatecustomerRequest $request)
    {
        $input = $request->all();

        $customer = $this->customerRepository->create($input);

        Flash::success('Customer saved successfully.');

        return redirect(route('members.customers.index'));
    }

    /**
     * Display the specified customer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $customer = $this->customerRepository->findWithoutFail($id);

        if (empty($customer)) {
            Flash::error('Customer not found');

            return redirect(route('members.customers.index'));
        }

        return view('members.customers.show')->with('customer', $customer);
    }

    /**
     * Show the form for editing the specified customer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $customer = $this->customerRepository->findWithoutFail($id);

        if (empty($customer)) {
            Flash::error('Customer not found');

            return redirect(route('members.customers.index'));
        }

        return view('members.customers.edit')->with('customer', $customer);
    }

    /**
     * Update the specified customer in storage.
     *
     * @param  int              $id
     * @param UpdatecustomerRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatecustomerRequest $request)
    {
        $customer = $this->customerRepository->findWithoutFail($id);

        if (empty($customer)) {
            Flash::error('Customer not found');

            return redirect(route('members.customers.index'));
        }

        $customer = $this->customerRepository->update($request->all(), $id);

        Flash::success('Customer updated successfully.');

        return redirect(route('members.customers.index'));
    }

    /**
     * Remove the specified customer from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $customer = $this->customerRepository->findWithoutFail($id);

        if (empty($customer)) {
            Flash::error('Customer not found');

            return redirect(route('members.customers.index'));
        }

        $this->customerRepository->delete($id);

        Flash::success('Customer deleted successfully.');

        return redirect(route('members.customers.index'));
    }
}

app/Http/Controllers/Members/purchaseOrderController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Requests\Members\CreatepurchaseOrderRequest;
use App\Http\Requests\Members\UpdatepurchaseOrderRequest;
use App\Repositories\Members\purchaseOrderRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class purchaseOrderController extends AppBaseController
{
    /** @var  purchaseOrderRepository */
    private $purchaseOrderRepository;

    public function __construct(purchaseOrderRepository $purchaseOrderRepo)
    {
        $this->purchaseOrderRepository = $purchaseOrderRepo;
    }

    /**
     * Display a listing of the purchaseOrder.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->purchaseOrderRepository->pushCriteria(new RequestCriteria($request));
        $purchaseOrders = $this->purchaseOrderRepository->all();

        return view('members.purchase_orders.index')
            ->with('purchaseOrders', $purchaseOrders);
    }

    /**
     * Show the form for creating a new purchaseOrder.
     *
     * @return Response
     */
    public function create()
    {
        return view('members.purchase_orders.create');
    }

    /**
     * Store a newly created purchaseOrder in storage.
     *
     * @param CreatepurchaseOrderRequest $request
     *
     * @return Response
     */
    public function store(CreatepurchaseOrderRequest $request)
    {
        $input = $request->all();

        $purchaseOrder = $this->purchaseOrderRepository->create($input);

        Flash::success('Purchase Order saved successfully.');

        return redirect(route('members.purchaseOrders.index'));
    }

    /**
     * Display the specified purchaseOrder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $purchaseOrder = $this->purchaseOrderRepository->findWithoutFail($id);

        if (empty($purchaseOrder)) {
            Flash::error('Purchase Order not found');

            return redirect(route('members.purchaseOrders.index'));
        }

        return view('members.purchase_orders.show')->with('purchaseOrder', $purchaseOrder);
    }

    /**
     * Show the form for editing the specified purchaseOrder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $purchaseOrder = $this->purchaseOrderRepository->findWithoutFail($id);

        if (empty($purchaseOrder)) {
            Flash::error('Purchase Order not found');

            return redirect(route('members.purchaseOrders.index'));
        }

        return view('members.purchase_orders.edit')->with('purchaseOrder', $purchaseOrder);
    }

    /**
     * Update the specified purchaseOrder in storage.
     *
     * @param  int              $id
     * @param UpdatepurchaseOrderRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatepurchaseOrderRequest $request)
    {
        $purchaseOrder = $this->purchaseOrderRepository->findWithoutFail($id);

        if (empty($purchaseOrder)) {
            Flash::error('Purchase Order not found');

            return redirect(route('members.purchaseOrders.index'));
        }

        $purchaseOrder = $this->purchaseOrderRepository->update($request->all(), $id);

        Flash::success('Purchase Order updated successfully.');

        return redirect(route('members.purchaseOrders.index'));
    }

    /**
     * Remove the specified purchaseOrder from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $purchaseOrder = $this->purchaseOrderRepository->findWithoutFail($id);

        if (empty($purchaseOrder)) {
            Flash::error('Purchase Order not found');

            return redirect(route('members.purchaseOrders.index'));
        }

        $this->purchaseOrderRepository->delete($id);

        Flash::success('Purchase Order deleted successfully.');

        return redirect(route('members.purchaseOrders.index'));
    }
}

app/Http/Controllers/Members/reservationOrderController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Requests\Members\CreatereservationOrderRequest;
use App\Http\Requests\Members\UpdatereservationOrderRequest;
use App\Repositories\Members\reservationOrderRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class reservationOrderController extends AppBaseController
{
    /** @var  reservationOrderRepository */
    private $reservationOrderRepository;

    public function __construct(reservationOrderRepository $reservationOrderRepo)
    {
        $this->reservationOrderRepository = $reservationOrderRepo;
    }

    /**
     * Display a listing of the reservationOrder.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->reservationOrderRepository->pushCriteria(new RequestCriteria($request));
        $reservationOrders = $this->reservationOrderRepository->all();

        return view('members.reservation_orders.index')
            ->with('reservationOrders', $reservationOrders);
    }

    /**
     * Show the form for creating a new reservationOrder.
     *
     * @return Response
     */
    public function create()
    {
        return view('members.reservation_orders.create');
    }

    /**
     * Store a newly created reservationOrder in storage.
     *
     * @param CreatereservationOrderRequest $request
     *
     * @return Response
     */
    public function store(CreatereservationOrderRequest $request)
    {
        $input = $request->all();

        $reservationOrder = $this->reservationOrderRepository->create($input);

        Flash::success('Reservation Order saved successfully.');

        return redirect(route('members.reservationOrders.index'));
    }

    /**
     * Display the specified reservationOrder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $reservationOrder = $this->reservationOrderRepository->findWithoutFail($id);

        if (empty($reservationOrder)) {
            Flash::error('Reservation Order not found');

            return redirect(route('members.reservationOrders.index'));
        }

        return view('members.reservation_orders.show')->with('reservationOrder', $reservationOrder);
    }

    /**
     * Show the form for editing the specified reservationOrder.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $reservationOrder = $this->reservationOrderRepository->findWithoutFail($id);

        if (empty($reservationOrder)) {
            Flash::error('Reservation Order not found');

            return redirect(route('members.reservationOrders.index'));
        }

        return view('members.reservation_orders.edit')->with('reservationOrder', $reservationOrder);
    }

    /**
     * Update the specified reservationOrder in storage.
     *
     * @param  int              $id
     * @param UpdatereservationOrderRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatereservationOrderRequest $request)
    {
        $reservationOrder = $this->reservationOrderRepository->findWithoutFail($id);

        if (empty($reservationOrder)) {
            Flash::error('Reservation Order not found');

            return redirect(route('members.reservationOrders.index'));
        }

        $reservationOrder = $this->reservationOrderRepository->update($request->all(), $id);

        Flash::success('Reservation Order updated successfully.');

        return redirect(route('members.reservationOrders.index'));
    }

    /**
     * Remove the specified reservationOrder from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $reservationOrder = $this->reservationOrderRepository->findWithoutFail($id);

        if (empty($reservationOrder)) {
            Flash::error('Reservation Order not found');

            return redirect(route('members.reservationOrders.index'));
        }

        $this->reservationOrderRepository->delete($id);

        Flash::success('Reservation Order deleted successfully.');

        return redirect(route('members.reservationOrders.index'));
    }
}

resources/views/members/purchase_orders/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Purchase Order
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'members.purchaseOrders.store']) !!}

                        @include('members.purchase_orders.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/members/purchase_orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Purchase Order
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($purchaseOrder, ['route' => ['members.purchaseOrders.update', $purchaseOrder->id], 'method' => 'patch']) !!}

                        @include('members.purchase_orders.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/members/purchase_orders/fields.blade.php
<!-- Customer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    {!! Form::number('customer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Course Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('course_id', 'Course Id:') !!}
    {!! Form::number('course_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Curso Field -->
<div class="form-group col-sm-6">
    {!! Form::label('curso', 'Curso:') !!}
    {!! Form::text('curso', null, ['class' => 'form-control']) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Duracion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('duracion', 'Duracion:') !!}
    {!! Form::number('duracion', null, ['class' => 'form-control']) !!}
</div>

<!-- Min Estudiantes Field -->
<div class="form-group col-sm-6">
    {!! Form::label('min_estudiantes', 'Min Estudiantes:') !!}
    {!! Form::number('min_estudiantes', null, ['class' => 'form-control']) !!}
</div>

<!-- Max Estudiantes Field -->
<div class="form-group col-sm-6">
    {!! Form::label('max_estudiantes', 'Max Estudiantes:') !!}
    {!! Form::number('max_estudiantes', null, ['class' => 'form-control']) !!}
</div>

<!-- Num Estudiantes Field -->
<div class="form-group col-sm-6">
    {!! Form::label('num_estudiantes', 'Num Estudiantes:') !!}
    {!! Form::number('num_estudiantes', null, ['class' => 'form-control']) !!}
</div>

<!-- Websitecourse Field -->
<div class="form-group col-sm-6">
    {!! Form::label('websiteCourse', 'Websitecourse:') !!}
    {!! Form::text('websiteCourse', null, ['class' => 'form-control']) !!}
</div>

<!-- Valor Field -->
<div class="form-group col-sm-6">
    {!! Form::label('valor', 'Valor:') !!}
    {!! Form::number('valor', null, ['class' => 'form-control']) !!}
</div>

<!-- Palabras Clave Field -->
<div class="form-group col-sm-6">
    {!! Form::label('palabras_clave', 'Palabras Clave:') !!}
    {!! Form::text('palabras_clave', null, ['class' => 'form-control']) !!}
</div>

<!-- Entity Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entity', 'Entity:') !!}
    {!! Form::text('entity', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Lastname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lastName', 'Lastname:') !!}
    {!! Form::text('lastName', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Celular Field -->
<div class="form-group col-sm-6">
    {!! Form::label('celular', 'Celular:') !!}
    {!! Form::text('celular', null, ['class' => 'form-control']) !!}
</div>

<!-- Website Field -->
<div class="form-group col-sm-6">
    {!! Form::label('website', 'Website:') !!}
    {!! Form::text('website', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('members.purchaseOrders.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/members/purchase_orders/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Purchase Orders</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('members.purchaseOrders.create') !!}">Crear registro</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('members.purchase_orders.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/members/purchase_orders/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Purchase Order
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('members.purchase_orders.show_fields')
                    <a href="{!! route('members.purchaseOrders.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/members/purchase_orders/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $purchaseOrder->id !!}</p>
</div>

<!-- Customer Id Field -->
<div class="form-group">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    <p>{!! $purchaseOrder->customer_id !!}</p>
</div>

<!-- Course Id Field -->
<div class="form-group">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{!! $purchaseOrder->course_id !!}</p>
</div>

<!-- Curso Field -->
<div class="form-group">
    {!! Form::label('curso', 'Curso:') !!}
    <p>{!! $purchaseOrder->curso !!}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{!! $purchaseOrder->descripcion !!}</p>
</div>

<!-- Duracion Field -->
<div class="form-group">
    {!! Form::label('duracion', 'Duracion:') !!}
    <p>{!! $purchaseOrder->duracion !!}</p>
</div>

<!-- Min Estudiantes Field -->
<div class="form-group">
    {!! Form::label('min_estudiantes', 'Min Estudiantes:') !!}
    <p>{!! $purchaseOrder->min_estudiantes !!}</p>
</div>

<!-- Max Estudiantes Field -->
<div class="form-group">
    {!! Form::label('max_estudiantes', 'Max Estudiantes:') !!}
    <p>{!! $purchaseOrder->max_estudiantes !!}</p>
</div>

<!-- Num Estudiantes Field -->
<div class="form-group">
    {!! Form::label('num_estudiantes', 'Num Estudiantes:') !!}
    <p>{!! $purchaseOrder->num_estudiantes !!}</p>
</div>

<!-- Websitecourse Field -->
<div class="form-group">
    {!! Form::label('websiteCourse', 'Websitecourse:') !!}
    <p>{!! $purchaseOrder->websiteCourse !!}</p>
</div>

<!-- Valor Field -->
<div class="form-group">
    {!! Form::label('valor', 'Valor:') !!}
    <p>{!! $purchaseOrder->valor !!}</p>
</div>

<!-- Palabras Clave Field -->
<div class="form-group">
    {!! Form::label('palabras_clave', 'Palabras Clave:') !!}
    <p>{!! $purchaseOrder->palabras_clave !!}</p>
</div>

<!-- Entity Field -->
<div class="form-group">
    {!! Form::label('entity', 'Entity:') !!}
    <p>{!! $purchaseOrder->entity !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $purchaseOrder->name !!}</p>
</div>

<!-- Lastname Field -->
<div class="form-group">
    {!! Form::label('lastName', 'Lastname:') !!}
    <p>{!! $purchaseOrder->lastName !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $purchaseOrder->email !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $purchaseOrder->phone !!}</p>
</div>

<!-- Celular Field -->
<div class="form-group">
    {!! Form::label('celular', 'Celular:') !!}
    <p>{!! $purchaseOrder->celular !!}</p>
</div>

<!-- Website Field -->
<div class="form-group">
    {!! Form::label('website', 'Website:') !!}
    <p>{!! $purchaseOrder->website !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $purchaseOrder->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $purchaseOrder->updated_at !!}</p>
</div>

resources/views/members/purchase_orders/table.blade.php
<div class="table-responsive">
    <table class="table" id="purchaseOrders-table">
        <thead>
            <tr>
                <th>Id</th>
        <th>Curso</th>
        <th>Descripcion</th>
        <th>Duracion</th>
        <th>Num Estudiantes</th>
        <th>Valor</th>
        <th>Entity</th>
        <th>Created At</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($purchaseOrders as $purchaseOrder)
            <tr>
                <td>{!! $purchaseOrder->id !!}</td>
            <td>{!! $purchaseOrder->curso !!}</td>
            <td>{!! $purchaseOrder->descripcion !!}</td>
            <td>{!! $purchaseOrder->duracion !!}</td>
            <td>{!! $purchaseOrder->num_estudiantes !!}</td>
            <td>{!! $purchaseOrder->valor !!}</td>
            <td>{!! $purchaseOrder->entity !!}</td>
            <td>{!! $purchaseOrder->created_at !!}</td>
                <td>
                    {!! Form::open(['route' => ['members.purchaseOrders.destroy', $purchaseOrder->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('members.purchaseOrders.show', [$purchaseOrder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('members.purchaseOrders.edit', [$purchaseOrder->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>